[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1N9FdHxi3FH2ljvwXBWfLjiWg8FiQA065PA6y_tnFesY/edit?usp=sharing"

worksheet = "1353146246"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
type = ""  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
auth_uri = ""
token_uri = ""
auth_provider_x509_cert_url = ""
client_x509_cert_url = ""